# Site Info
title:              "Code X"
description:        "A curation of helpful code snippets."
google_verify:       # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "CodeX" # Your name here
author_email:       codex@gmail.com # Your email here
author_gravatar:     # Your Gravatar md5 hash here for logo
twitter_username:    # Your Twitter username here
github_username:     # Your GitHub username here

# Site Settings
url:                http://jk.dev # main url
baseurl:             # for gh-pages
permalink:          /blog/:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - octopress-minify-html

env: production

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
